### PR TITLE
Added ability to manage multiple paths

### PR DESCRIPTION
**Pull request by farfilli**

### CODE REVIEW

**Comment by rmcanany** [comment]
I have it pulled down.  It's complaining about Dim xlApp As Excel.Application in CommonTasks.ReadExcel.  It says "Type Excel.Application is not defined".  

I tried to add a Reference to the Project, but that didn't show up on the list.  I don't have Excel installed.  Could that be the cause?

I've commented it out for now and am going to start playing around with it.  It looks fantastic!  I'll keep you posted.

**Comment by rmcanany** [comment]
Rather than messing with branches, I went ahead and merged everything.  

Regarding the outdated flag, it's this one, right?  
    Private ListViewFilesOutOfDate As Boolean

**Comment by farfilli** [comment]
Yes that one, unless you believe it's still needed for some reason.

In my opinion the list should be in control of the user and avoid any automatic reload.

I would also give a look at the reconcileform... I see it called quite a lot of times and it's a big sub; wouldn't be better that each control take care of its own form changes? It would be a massive work to rewrite it though

To finish the list page work I would move also the last controls to something more integrated.

**Comment by rmcanany** [comment]
All good ideas.  I don't remember exactly why I put everything in ReconcileFormChanges().  I think it had to do with certain Events triggering other Events.  Anyway, I'll take a look.  

I tried the top level assy and folders and got an exception after clicking Update.  It was at Line 60 in Form1.FileHelperFunctions.vb.  It says 'Add failed. Duplicate key value supplied.'

Looking at tmpList.Item(1), the Key is Nothing, tmpList.Item(2), the Key is 'Form1'.  That doesn't seem right.

Here were my selections:

Top level assembly: ..\Projects\Project_1\project-1_toplevelassy.asm
Top level asm folder: ..\Projects\Project_1
Top level asm folder: ..\Projects\Common_Parts

I'm a little lost on ListView.  Do you have any ideas?

**Comment by farfilli** [comment]
Should be fixed now, let me do some tests

**Comment by farfilli** [comment]
Fixed with last Pull request, it was a last-minute edit not tested

**Comment by farfilli** [comment]
Just a note, the folder that contains the top-level assembly is automatically considered in the search so there is no need to add it again.

**Comment by farfilli** [comment]
Managing multiple paths should be complete now, there is just need to remove all unused code

**Pull request merged**
