### PR TITLE
Bug fixing

### PR DESCRIPTION
**Pull request by farfilli**
Collection key was not correctly inserted

### CODE REVIEW

**Comment by rmcanany** [comment]
I must be doing something wrong.  I only got one file...
tla_search

**Comment by farfilli** [comment]
Did you check top down in configuration page?

**Comment by rmcanany** [comment]
Yes.

**Comment by farfilli** [comment]
That is strange, I did try with few asm, need a better testing.

The only part in list is the one in same folder as the asm ?

Perhaps there is a bug in the recursive folder search.

If you able to debug it or I will do it tomorrow.

**Comment by rmcanany** [comment]
I'm doing it right now.  The only part listed is the one in the _other_ folder.  I'm going to see what FoundFiles = TLAU.GetLinks is returning and go from there.

I'll also make a better test case -- with drafts, etc.  I'll upload it later today.

**Comment by rmcanany** [comment]
It's overwriting FoundFiles when it goes through the loop a second time.  Also, the top level assembly file, even though returned by TLAU, is not showing up on the list of files to process.

If you don't mind, I'll let you handle this one and I'll get busy with my cleanup project.  Sound OK?

**Comment by farfilli** [comment]
Yes, I thought it was something like this. I'll fix it tomorrow, it should be an easy one

**Comment by farfilli** [comment]
Ok, I solved the problem by creating an intermediate list of strings to collect all the results.
I have done some tests on my file NAS and found out that if you have a large archive as I do, the wait for the result is very big. We do not use FastSearch due to the fact our NAS relies on a Linux OS and the service can't be installed.

Wouldn't be interesting to create a method to read all the links inside an ASM and its occurrences to populate a list? That would be much faster. Where used files can be retrieved optionally by the fast search or disk search.

**Pull request merged**
