### PR TITLE
Property Columns Implementation

### PR DESCRIPTION
**Pull request by farfilli**
This is a preliminary implementation of #139 

I created some subs that need to be moved to the correct location and possibly shared to be used in the entire program.
Also, an implementation to save the columns from one session to another would be useful @rmcanany I would be glad if you take care of this

I have added comments to the code

### CODE REVIEW

**Comment by rmcanany** [comment]
That's slick!  I'll take care of the save/retrieve.  It would be nice if we could use FormPropertyPicker to populate the list.  It might be easier if I did that part since it's my code.  Let me know.

**Comment by farfilli** [comment]
Yes sure, I wanted to take care of the UI first, if you know any part of code already made go on with it :)
Also, the list of the selected columns has a checkbox that I wanted to use to show-hide temporarily I don't know if it's useful or remove it. At the moment it does nothing.

**Comment by rmcanany** [comment]
OK, will do.  

For me, it will be a set and forget thing.  So I wouldn't need to temporarily show/hide columns.  That said, it wouldn't bother me either.  We would have to track the checkbox state, but that could easily be done using a Dict instead of List.

**Comment by rmcanany** [comment]
Added ListOfColumns save/retrieve and prop selection from dialog.  Minimally tested.

**Comment by rmcanany** [comment]
Moved UpdatePropertiesColumns to UtilsFileList

**Pull request merged**
