### PR TITLE
Enabled drag & drop of files

### PR DESCRIPTION
**Pull request by farfilli**
It's now possible to drop files on the list, files with inactive extension filters will be skipped

ListView Header visible for user column resizing
Property filter and text filter editable even when not active; make it easier setup the filter and then apply

RMB menu item to process selected files

Removed usage of FFMPEG and moved CropImage() in commontasks.vb

### CODE REVIEW

**Comment by farfilli** [comment]
It seems the ListViewFiles has lost its group, It should look like this:

image

**Comment by rmcanany** [comment]
OK.  I've got to go into the office this morning.  I'll look at it this afternoon.

Looking at Form1.Designer.vb (the text file, not the graphics)  it seems to have increased the number indicators on those objects.
        Dim ListViewGroup7 As System.Windows.For...
        Dim ListViewGroup8 As System.Windows.For...
        Dim ListViewGroup9 As System.Windows.For...
...

**Comment by farfilli** [comment]
Ttry to close and reopen the solution, it happened to me before its just VS that gets crazy

**Comment by rmcanany** [comment]
That didn't fix it for me.

**Comment by farfilli** [comment]
I had a look at your last commits and there is no difference with my last pull request so it happened after the merge

**Comment by farfilli** [comment]
You are right it has increased at you side

**Comment by farfilli** [comment]
image

**Comment by rmcanany** [comment]
Yeah, that's it.  I gotta go now.  I'll change that stuff back later today.

**Pull request merged**
