### PR TITLE
Regenerate missing flat model

### PR DESCRIPTION
**Pull request by ChrisNeCle**
In very rare conditions that seem to coincide with CopyConstruction features, a part can be "missing" the 3D flat model. This is completely undetectable via the GUI as this model is automatically regenerated when entering the Flatten environment.

This issue impacts interop software that interacts with the flat models via the API in the background. Consider the following (incomplete C#) code:

```C#
partDoc = (SE.SolidEdgeDocument)application.Documents.Open(path);
sheetMetalDoc = (SEPar.SheetMetalDocument)partDoc;
var flatModels = sheetMetalDoc.FlatPatternModels;
var flatModel = flatModels.Item(1);
flatModel.MakeActive();
sheetMetalDoc.SaveCopyAs($"{sheetMetalDoc.Name}.stp");
```

Under normal circumstances, if you have the "Use Current Configuration" option set in your STEP Part Simplification Export Options, this code will output a STEP file of the flat model.

image

If you run this code on a part with the "missing" flat model, it will produce no errors but will output an empty STEP file with no geometry. This causes issues with CAM and other software that exports flat models from Solid Edge parts.

This script will open a part in the foreground, switch to the flatten environment, then save the part. This regenerates the flat model and the newly saved part will no longer break third party software.

I added this under the Update category as it seemed most appropriate. I can resubmit under Edit if that makes more sense.

Attached is a ZIP containing demonstration parts for posterity. The -BEFORE PSM is in a broken state. The -BEFORE STP file is the output of the broken PSM when saving via the API. I tested this part using the code in this PR then ran it through an API-based STEP export again and the -AFTER STP file was correctly generated. I no longer have a large assembly to test it on as I've corrected all of my known bad assemblies with my own original script already.

Ideally, and in the original code, this would check for the bad STEP files before performing the regen and save. That adds additional dependencies via a STEP file parsing library so it is not included in this PR. Switching environments and saving should be non-destructive as it's not forcing any changes, just allowing Solid Edge to update the part state as it would through normal operation of the GUI.

I added read-only, background, and and FlatpatternModel count checks. Part processing logic is in an If statement that checks exist status before starting, as it's a resource-intensive foreground operation that requires UI updates. No sense processing a part if it's just going to throw an error code afterward. Let me know if there's anything I can do to clean this up to keep it more within your project style.

I should probably include a PR for documentation updates as well. Since this won't make it to release soon, I can look up the structure for that another day.

[MissingFlatModelTest.zip](https://github.com/rmcanany/SolidEdgeHousekeeper/files/15311320/MissingFlatModelTest.zip)

### CODE REVIEW

**Comment by rmcanany** [comment]
That's great!  Thank you!

I have tried in the past to include `STP Flat` as an option for `Save Model As`, but could never get it to work.  It sounds like you have figured it out.  Once I get back on Housekeeper, I may hit you up for some sample code.

**Comment by ChrisNeCle** [comment]
The required config is stored in `C:\Program Files\Siemens\Solid Edge 2022\Preferences\Translators\STEP.INI` and the settings are non defaults.

I haven't written the logic to automatically write the config changes required to export the flat STEP, mostly out of laziness because my SE config is already set up correctly and I didn't want to parse the INI files. I'd be happy to assist when you're ready to implement it.

**Comment by rmcanany** [comment]
Yeah, sounds good.

You don't need to do anything extra for the documentation, by the way.  Every time Housekeeper starts on my machine, it picks up the `HelpText` property for each `Task` and appends it to `Readme.md`.  Same thing for the 'HelpURL'.

**Comment by rmcanany** [comment]
@ChrisClems I renamed this task to `UpdateFlatPattern`, but rereading the documentation, it appears the main intent was to generate one if it doesn't exist.  I just tried deleting the flat pattern and it didn't appear to add a new one.  Ideas?

**Comment by ChrisClems** [comment]
> @ChrisClems I renamed this task to `UpdateFlatPattern`, but rereading the documentation, it appears the main intent was to generate one if it doesn't exist. I just tried deleting the flat pattern and it didn't appear to add a new one. Ideas?

The flat pattern being missing wasn't an issue. This fixed an edge case problem in which the flat _model_ specifically appears to be missing from the part file even though it shows an object in the collection. This is something that turned up in our parts library over time, so I wasn't able to reproduce any specific actions that caused it. I was noticing about 2% of our parts seemed to be impacted. The common link seemed to be CopyConstructions but I couldn't prove it as I couldn't recreate it.

This would manifest as empty STEP, STL, etc. files being produced when you'd use the following code:

```
partDoc = (SE.SolidEdgeDocument)application.Documents.Open(path);
sheetMetalDoc = (SEPar.SheetMetalDocument)partDoc;
var flatModels = sheetMetalDoc.FlatPatternModels;
var flatModel = flatModels.Item(1);
flatModel.MakeActive();
sheetMetalDoc.SaveCopyAs($"{sheetMetalDoc.Name}.stp");
```

The STEP file will be written. There will be no errors. However, it will contain no geometry at all.

It was almost impossible to catch in the GUI. The steps to remedy it is to switch to the flatten environment then save the part. To save a flat model as a STEP in the GUI you must enter the flatten environment, so there is no way to "see" the issue. If I ran this code completely in the foreground with the part visible, it would end up in a state where I was in the flatten environment, but no model was displayed on the screen. Only an explicit switch to the flatten environment using that command constant would fix it.

This issue becomes a problem for CAM and other software that needs to export common exchangeable formats for flat models.

It's been a long time since I addressed this, but I dug through my old files, and I think the attached part had the issue.

[124697-01.zip](https://github.com/user-attachments/files/15955775/124697-01.zip)

**Comment by rmcanany** [comment]
Oh, got it.  Would it hurt anything if I added functionality to update the flat pattern to that Task?

**Comment by rmcanany** [comment]
OK, thank you.  I added the update code.  I'll do some testing later this week.

**Comment by ChrisClems** [comment]
> OK, thank you. I added the update code. I'll do some testing later this week.

Please let me know what you find out. If you can duplicate my findings, I will throw together some sample code and submit an IR.

**Pull request merged**
