### PR TITLE
Implemented Property Filter

### PR DESCRIPTION
**Pull request by farfilli**
Moved property search on filelist
It need an extensive test cause I didn't had more time

### CODE REVIEW

**Comment by rmcanany** [comment]
I will test it!

**Comment by farfilli** [comment]
Consider that concurrent property filter and text filter are not working at the moment.
I will need to intersect the results of the two filters in case it's a needed condition.

Otherwise the activation of one will deactivate the other.

What do you think?

**Comment by rmcanany** [comment]
I actually do use those together at times.

Note, 'File search' is supposed to be a wildcard search.  Take a look at:
Form1.FileHelperFunctions.FileWildcardSearch

You'll see it uses the VB 'Like' function to compare the filename to the wildcard sting.  The wildcard string is in new_ComboBoxFileSearch.Text

I think in Form1.TextFilter() this
If item.Text.Contains(new_ComboBoxFileSearch.Text)

should be (assuming item.Text is the filename, not the full path)
If item.Text Like new_ComboBoxFileSearch.Text

**Comment by rmcanany** [comment]
Oh, and at least in my case, the wildcard search removes many files from the list.  In my code I did the wildcard after the property filter.  That's backwards.

**Comment by farfilli** [comment]
Yes item.text is the filename, you can change the code and test it, If it work you can commit it.

In my opinion wildcard filter should come first cause it shorten the list for the property search that is more time consuming.

One more thing, why use DM for property search and not the FileProperty class ? Is it faster? I never conducted a benchmark but you don't have to start DM in that way

**Comment by rmcanany** [comment]
OK I'll give a try.  

Right, that's what I meant about doing the wildcard search first.  I had it backwards before.

I didn't know about the FileProperty class.  I'll look into it.  Later, that is...

**Comment by rmcanany** [comment]
That seems to work.  I went ahead and pushed it to GitHub.

I'm going to study the flow starting with the Update button to see if I can get the wildcard search ahead of the property filter.

**Comment by farfilli** [comment]
As it is made now they both start from a full list (backup list)

My idea is to create an intermediary filtered list to use for property search

**Comment by rmcanany** [comment]
OK.  Can I let you have that one?  I need to get up to speed on ListView.  I'm going to do that this afternoon.

Not sure I mentioned this before, but I completely agree that the only way to update the list should be with the Update button.  I wonder if any time a "Source" is added or deleted, the file list should be cleared.  What do you think?

**Comment by farfilli** [comment]
Well I have an idea that it has to be implemented, it just will make things a bit more complicated.

The idea is to create a collection of results for each source so if you delete a source it delete its own items and if you add a source you can update just that one.

Ideally create a class source with its properties and methods to call.

**Comment by farfilli** [comment]
At the moment just managed some concurrent filtering, will see in the future if I have time to create a proper class to manage sources

**Pull request merged**
